name: Coverage report

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.yml"
  pull_request:
    branches:
      - dev
    paths-ignore:
      - "**.md"
      - "**.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: |
          pub global activate test_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          test_coverage
      - name: Check 95% code coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: "./coverage/lcov.info"
          min_coverage: 95
          exclude: "**/*.freezed.dart **/*.g.dart **/*.gr.dart"

      - name: Upload coverage data to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: "./coverage/lcov.info"
          fail_ci_if_error: true
          verbose: true
